# Generated by Django 3.1.4 on 2021-01-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Telepnone_number',
            new_name='telepnone_number',
        ),
    ]
