# Generated by Django 3.1.4 on 2021-01-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgames', '0002_auto_20210101_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='telepnone_number',
            new_name='telephone_number',
        ),
    ]
